import './styles/global.css';
export { MinidAlert } from './components/alert.component.ts';
export { MinidButton } from './components/button.component.ts';
export { MinidCheckbox } from './components/checkbox.component.ts';
export { MinidCodeInput } from './components/code-input.component.ts';
export { MinidCombobox } from './components/combobox.component.ts';
export { MinidCountdown } from './components/countdown.component.ts';
export { MinidDropdown } from './components/dropdown.component.ts';
export { MinidHeading } from './components/heading.component.ts';
export { MinidHelptext } from './components/helptext.component.ts';
export { MinidIcon } from './components/icon/icon.component.ts';
export { MinidLink } from './components/link.component.ts';
export { MinidMenu } from './components/menu.component.ts';
export { MinidMenuItem } from './components/menu-item.component.ts';
export { MinidDialog as MinidModal } from './components/modal.component.ts';
export { MinidParagraph } from './components/paragraph.component.ts';
export { MinidPhoneInput } from './components/phone-input.component.ts';
export { MinidPopup } from './components/popup.component.ts';
export { MinidQrCode } from './components/qr-code.component.ts';
export { MinidSearch } from './components/search.component.ts';
export { MinidSpinner } from './components/spinner.component.ts';
export { MinidTextfield } from './components/textfield.component.ts';
export { MinidTooltip } from './components/tooltip.component.ts';
export { countryLabelsNO } from './utilities/countries.ts';
