name: Build and Publish Web Components

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:

    permissions:
      contents: write
      id-token: write

    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
          scope: '@felleslosninger'
          token: ${{ secrets.NPM_TOKEN }}

      - name: Increment version
        run: |
          git config user.email ""
          git config user.name ""
          npm --no-git-tag-version version patch

      - name: Commit package.json
        run: |
          echo "Committing changes..."
          VERSION=$(node -p "require('./package.json').version")
          file=package.json
          CONTENT=$(base64 -w 0 $file)
          FILENAME=$(basename $file)
          SHA=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/repos/${{ github.repository }}/contents/$file?ref=main | jq -r .sha)
          if [ "$SHA" == "null" ]; then
           SHA=""
          fi
          curl -s -X PUT -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
           -d "{\"message\":\"[skip actions] new version $VERSION\", \"content\":\"$CONTENT\", \"branch\":\"main\", \"sha\":\"$SHA\"}" \
           https://api.github.com/repos/${{ github.repository }}/contents/$file

      - name: Install dependencies
        run: yarn install

      - name: Build web components
        run: yarn build

      #################################
      # Publish to public npm repo
      ################################
      - name: Publish to public npm repo
        run: |
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc
          npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

      #################################
      # Publish to MinID CDN
      ################################
      - name: Setup SSH Deploy Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.CDN_DEPLOY_KEY }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}

      - name: Clone CDN Repo (using SSH)
        run: |
          git clone git@github.com:felleslosninger/minid-cdn.git cdn

      - name: Build CDN version, and copy files to CDN repo
        run: |
          yarn build:cdn
          cd cdn
          VERSION=$(node -p "require('../package.json').version")
          mkdir -p minid-elements/${VERSION}                    
          cp -r ../dist-cdn/* minid-elements/$VERSION
          cd minid-elements
          echo $VERSION > version.txt
          ln -sfn $VERSION latest      
          mkdir -p $VERSION/theme
          cp -r ../../node_modules/@digdir/designsystemet-theme/brand/* $VERSION/theme/

      - name: Commit Changes to CDN Repo (using SSH)
        run: |
          VERSION=$(node -p "require('./package.json').version")
          cd cdn
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          git commit -m "[skip actions] Deploy version $VERSION to CDN"
          git push origin main
