name: Build and Publish Web Components

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:

    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Increment version
        run: |
          npm version patch -m  "[skip actions] Bump version to %s"
          VERSION=$(node -p "require('./package.json').version")
          echo "New version: $VERSION"
          git tag ${VERSION}
          git push --follow-tags          

      - name: Install dependencies
        run: yarn install

      - name: Build web components
        run: yarn build

      - name: Configure GitHub Package Registry
        run: |
          npm config set //npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}
          npm config set @felleslosninger:registry=https://npm.pkg.github.com/

      - name: Publish to GitHub Packages
        run: npm publish