name: Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      id-token: write
      packages: write
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Set git identity
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - uses: ./.github/actions/gh-setup # this installs Node.js, pnpm and dependencies

      - name: Create Release Pull Request or Publish to npm
        id: changesets
        # Use the upstream Changesets GitHub Action for release PR creation and publishing
        uses: changesets/action@v1
        with:
          publish: pnpm release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: "" # https://github.com/changesets/changesets/issues/1152#issuecomment-3190884868
          NPM_CONFIG_PROVENANCE: true

      #################################
      # Publish to MinID CDN
      ################################
      - name: Setup SSH Deploy Key
        if: steps.changesets.outputs.published == 'true'
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.CDN_DEPLOY_KEY }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}

      - name: Clone CDN Repo (using SSH)
        if: steps.changesets.outputs.published == 'true'
        run: |
          git clone git@github.com:felleslosninger/minid-cdn.git cdn

      - name: Build CDN version, and copy files to CDN repo
        if: steps.changesets.outputs.published == 'true'
        run: |
          pnpm run build:cdn
          cd cdn
          VERSION=$(node -p "require('../package.json').version")
          mkdir -p minid-elements/${VERSION}                    
          cp -r ../dist-cdn/* minid-elements/$VERSION
          cd minid-elements
          echo $VERSION > version.txt
          ln -sfn $VERSION latest      

      - name: Commit Changes to CDN Repo (using SSH)
        if: steps.changesets.outputs.published == 'true'
        run: |
          VERSION=$(node -p "require('./package.json').version")
          cd cdn
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          git commit -m "[skip actions] Deploy version $VERSION to CDN"
          git push origin main