name: Build and Publish Web Components

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:

    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Increment version
        run: |
          git config user.email ""
          git config user.name ""
          npm --no-git-tag-version version patch

      - name: Commit package.json
        run: |
          echo "Committing changes..."
          VERSION=$(node -p "require('./package.json').version")
          file=package.json
          CONTENT=$(base64 -w 0 $file)
          FILENAME=$(basename $file)
          SHA=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/repos/${{ github.repository }}/contents/$file?ref=main | jq -r .sha)
          if [ "$SHA" == "null" ]; then
           SHA=""
          fi
          curl -s -X PUT -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
           -d "{\"message\":\"[skip actions] new version $VERSION\", \"content\":\"$CONTENT\", \"branch\":\"main\", \"sha\":\"$SHA\"}" \
           https://api.github.com/repos/${{ github.repository }}/contents/$file

      - name: Install dependencies
        run: yarn install

      - name: Build web components
        run: yarn build

      - name: Configure GitHub Package Registry
        run: |
          npm config set //npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}
          npm config set @felleslosninger:registry=https://npm.pkg.github.com/

      - name: Publish to GitHub Packages
        run: npm publish