name: Build and Publish Storybook to GitHub Pages

on:
  push:
    branches:
      - 'main'

permissions:
  contents: read
  pages: write
  id-token: write

# List of jobs
jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.build-publish.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js, pnpm and install dependencies
        uses: ./.github/actions/gh-setup
        with:
          npm-token: ${{ secrets.NPM_TOKEN }}

      #👇 Add Storybook build and deploy to GitHub Pages as a step in the workflow
      - uses: bitovi/github-actions-storybook-to-github-pages@v1.0.3
        with:
          install_command: echo "Dependencies already installed"
          build_command: pnpm storybook:build # default: npm run build-storybook
          path: storybook-static # default: dist/storybook
          checkout: false # default: true
