name: PR Check

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Setup Node.js, pnpm and install dependencies
        uses: ./.github/actions/gh-setup

      - name: Build web components
        run: pnpm build

      - name: Build CDN version
        run: pnpm build:cdn

      - name: Build Storybook
        run: pnpm storybook:build
